server:
  port: 8888
spring:
  application:
    name: sso-server
  redis:
    host: 127.0.0.1
    password:
    jedis:
      pool:
        min-idle: 0
        max-idle: 8
        max-wait: 2000
        max-active: 8
    port: 6379
    database: 0
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT%2B8
    username: root
    password: 123456
  jpa:
    database: mysql
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
  thymeleaf:
    prefix: classpath:/templates/html/
    suffix: .html
    encoding: UTF-8
    cache: false
  resources:
    static-locations: classpath:/static/
eureka:
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://root:123456@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
